# Generated by Django 4.1.7 on 2023-03-12 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_feedback_user_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=6000, verbose_name='Содержание объявления'),
        ),
    ]
