# Generated by Django 4.1.7 on 2023-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Комментарий принят автором'),
        ),
    ]
