# Generated by Django 4.1.7 on 2023-03-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Аватар'),
        ),
    ]
