# Generated by Django 4.1.7 on 2023-03-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='media/default.jpg', upload_to='media/profile_images', verbose_name='Аватар'),
        ),
    ]
