# Generated by Django 4.1.7 on 2023-03-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_images', verbose_name='Аватар'),
        ),
    ]
